"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import {
  BrainCircuit,
  FileText,
  Map,
  GraduationCap,
  LineChart,
  ArrowRight,
  Sparkles,
} from "lucide-react";

const values = [
  {
    icon: BrainCircuit,
    title: "AI-First Approach",
    description:
      "Every feature is built around AI, giving you insights and recommendations that adapt to your specific background and goals.",
  },
  {
    icon: GraduationCap,
    title: "Interview Excellence",
    description:
      "Practice with role-specific questions generated by AI and get detailed feedback to sharpen your answers.",
  },
  {
    icon: LineChart,
    title: "Industry Intelligence",
    description:
      "Stay ahead with real-time salary data, demand trends, and market signals for your industry.",
  },
  {
    icon: Map,
    title: "Clear Career Path",
    description:
      "Get a personalized roadmap from your current role to your target, with concrete milestones and skills to develop.",
  },
  {
    icon: FileText,
    title: "Resume & Cover Letters",
    description:
      "Build an ATS-optimized resume and generate tailored cover letters for every application in seconds.",
  },
  {
    icon: Sparkles,
    title: "Always Improving",
    description:
      "GuidelyAI learns from industry signals and continuously updates recommendations to stay relevant.",
  },
];

const container = {
  hidden: {},
  visible: { transition: { staggerChildren: 0.08 } },
};

const item = {
  hidden: { opacity: 0, y: 16 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.45 } },
};

export default function AboutPage() {
  return (
    <main className="min-h-screen bg-background">
      {/* Hero */}
      <section className="relative py-24 overflow-hidden border-b border-border">
        <div className="absolute inset-0 -z-10 bg-white [background-image:radial-gradient(#e5e7eb_1px,transparent_1px)] [background-size:20px_20px]" />
        <div className="absolute inset-0 -z-10 bg-[radial-gradient(ellipse_70%_50%_at_50%_-10%,rgba(142,45,226,0.1),transparent)]" />

        <div className="container mx-auto px-4 md:px-6 text-center">
          <motion.div
            initial={{ opacity: 0, y: 14 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
          >
            <Badge variant="outline" className="mb-6 gap-1.5">
              <Sparkles className="h-3.5 w-3.5" />
              About GuidelyAI
            </Badge>
          </motion.div>

          <motion.h1
            className="text-4xl font-bold tracking-tight gradient-title md:text-6xl max-w-3xl mx-auto"
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.1 }}
          >
            Your AI-Powered Career Mentor
          </motion.h1>

          <motion.p
            className="mt-6 max-w-2xl mx-auto text-lg text-muted-foreground"
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.2 }}
          >
            GuidelyAI was built for professionals who want more than generic advice.
            We combine AI intelligence with real industry data to give you a personal
            career edge — whether you're just starting out, switching paths, or leveling up.
          </motion.p>

          <motion.div
            className="mt-10 flex flex-wrap gap-4 justify-center"
            initial={{ opacity: 0, y: 14 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.3 }}
          >
            <Link href="/dashboard">
              <Button size="lg" className="gap-2 px-8">
                Get Started
                <ArrowRight className="h-4 w-4" />
              </Button>
            </Link>
            <Link href="/">
              <Button size="lg" variant="outline" className="px-8">
                Back to Home
              </Button>
            </Link>
          </motion.div>
        </div>
      </section>

      {/* Mission */}
      <section className="py-20 border-b border-border bg-muted/30">
        <div className="container mx-auto px-4 md:px-6 max-w-3xl text-center">
          <Badge variant="outline" className="mb-4">Our Mission</Badge>
          <h2 className="text-3xl font-bold tracking-tight md:text-4xl mb-6">
            Democratizing career success
          </h2>
          <p className="text-muted-foreground text-lg leading-relaxed">
            Top-tier career coaching used to be expensive and exclusive. GuidelyAI changes that.
            We believe every professional deserves access to intelligent, personalized guidance —
            not just those who can afford a $500/hr coach. Our platform brings that same quality
            to anyone with ambition.
          </p>
        </div>
      </section>

      {/* What we offer */}
      <section className="py-20 border-b border-border">
        <div className="container mx-auto px-4 md:px-6">
          <div className="text-center mb-14">
            <Badge variant="outline" className="mb-4">What We Offer</Badge>
            <h2 className="text-3xl font-bold tracking-tight md:text-4xl">
              Built for every stage of your career
            </h2>
          </div>

          <motion.div
            className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 max-w-5xl mx-auto"
            variants={container}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: "-60px" }}
          >
            {values.map(({ icon: Icon, title, description }) => (
              <motion.div key={title} variants={item}>
                <Card className="h-full border-border hover:border-primary/30 transition-colors">
                  <CardContent className="pt-6 pb-6 space-y-3">
                    <div className="p-2 w-fit rounded-lg bg-muted">
                      <Icon className="h-5 w-5 text-primary" />
                    </div>
                    <h3 className="font-semibold">{title}</h3>
                    <p className="text-sm text-muted-foreground leading-relaxed">{description}</p>
                  </CardContent>
                </Card>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-20">
        <div className="container mx-auto px-4 md:px-6">
          <div className="max-w-2xl mx-auto text-center border border-border rounded-2xl bg-muted/30 px-8 py-14">
            <h2 className="text-3xl font-bold tracking-tight mb-4">
              Ready to take the next step?
            </h2>
            <p className="text-muted-foreground mb-8">
              Join GuidelyAI and get a clear, AI-powered path to your next role.
            </p>
            <Link href="/dashboard">
              <Button size="lg" className="gap-2 px-8">
                Start for Free
                <ArrowRight className="h-4 w-4" />
              </Button>
            </Link>
          </div>
        </div>
      </section>
    </main>
  );
}
